language: node_js
node_js:
- 14
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: salty-island-09434
  api_key:
    secure: FdVzi0eh1WSgAY7t2aleg6oFdL0FWYS5ywq7xTJgLZSYTmgXa23nZddbacHaKb9U0jG2oPFVx2Q+BX1tgOyiN7zNjneXGVW9t4UJOD1ezm4qPi/es2Ago5aulb8VeAKFY6VDBdyMWKLX3gwOuxTiN0HRm0b6N8QiEZgL2GASCtXdiVBRtdTl5mAHPt43LE0HDMIjxK4JpcdTj1bx8P5o7kmzeNYmDSiGyJ5eZ3EEL1cngNL1hsNcncJCPDH7CIw5IxfY2ImOtPfKXcLVjfyhw5lZIWkyRAnI5iIy0prIiW+O8oe/tt8/5A/9WEWkfOisYqAZzOfXevEY9If4IHiWL3MB3UgxVejwnT/+W3lvSxkhmJkuvSA3ipDxbVNsFuwquxtbVdSx/aLqMCqTBZSuUPGlAi2KHoOuCybkxr0B+MkywAAZ/7d3Tbn8wxwZG6s7z7C4nKoZ4kepsdyaddixjq5WQ55lS/Zb2eDhzopx+DspjjJ6ofwt6MAfoNs4DsnzM0m7cRoo2yEku53NG1cnCYmeaH+YTTcijufX7/Pta7JBSceC0rdlx3u5bLQXEWDaMdWDqqdGIycpG/CuT2P+ozs445IP2p1QGwcbsrOH/RHsoV+U+FlJqdZGL48wUigIs2H7+10x++AXsNcvFOR3n8oLVyKSnxx8Bnzvz07LZBY=
